config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'login' , to: 'sessions#new'
  get 'profile', to: 'pages#profile' 
  get 'seattlehostlist' , to: 'pages#seattle_host_list'
  get 'tokyohostlist' , to: 'pages#tokyo_host_list'
  get 'search', to: 'events#search'
  post 'search', to: 'reservations#create'

  devise_for :users
  resources :events
  resources :yoyakus
  resources :reservations
  
  # get 'pages/profile'
end

app/models/abledate.rb
class Abledate < ActiveRecord::Base
  def search
    scoped = Abledate.scoped
    @products = @products.where(t[:code].matches("%#{code}%")) if code.present?
    scoped
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :host, class_name: "User"
  belongs_to :guest, class_name: "User"
end

app/models/event.rb
class Event < ActiveRecord::Base
    belongs_to :user
    validates :user_id, presence: true
    has_many :yoyakus
    has_many :reservations
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :events
  has_many :yoyakus
  has_many :reservations
end

app/models/yoyaku.rb
class Yoyaku < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/controllers/abledates_controller.rb
class AbledatesController < ApplicationController
  def index
    @abledate_form = Abledate.new params[:abledate_form]
    @abledates = @abledate_form.search
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    # devise_parameter_sanitizer.for(:sign_up) { |u| u.permit( :username, :location )}
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:sign_up) << :location
    devise_parameter_sanitizer.for(:account_update) << :username
    devise_parameter_sanitizer.for(:account_update) << :location
    devise_parameter_sanitizer.for(:account_update) << :hosting
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to profile_path, notice: 'You set an available date! ' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to profile_path, notice: 'Booked!' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def search
    # @event = Event.new #in order to avoid errors
    if params[:start]
      date_hash = params[:start]
      date_string = "#{date_hash['(1i)']}-#{date_hash['(2i)']}-#{date_hash['(3i)']}"
      # @dates = Event.where("start = ?", params[:start])
      @dates = Event.where("start = ?", date_string)
    end
  end
  
  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:start, :end)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # before_action :set_user, only: [:home, :profile, :seattle_host_list, :tokyo_host_list]
  
  def home
    if user_signed_in?
      redirect_to profile_path
    end
  end

  def profile
    @user = current_user
    @reservations = @user.reservations
    @events = Event.all
  end
  
  def seattle_host_list
    @seattlehosts = User.where(location: "Seattle").where(hosting: true)
  end
  
  def tokyo_host_list
    @tokyohosts = User.where(location: "Tokyo").where(hosting: true)
  end
=begin  
  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :location, :hosting)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
=end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    
  def new
  end
  
  def create
  @reservation = current_user.reservations.build(reservation_params)
    if @reservation.save
      flash[:success] = "Reservation made!"
      redirect_to profile_path
    else
      redirect_to search_path
    end
  end

  private
  def reservation_params
    # params.require(:reservation)
  end
  
end

app/controllers/yoyakus_controller.rb
class YoyakusController < ApplicationController
  
  def new
  end
  
  def create
  @yoyaku = current_user.yoyakus.build(yoyaku_params)
    if @yoyaku.save
      flash[:success] = "Reservation made!"
      redirect_to profile_path
    else
      redirect_to search_path
    end
  end

  private
  def yoyaku_params
    # params.require(:yoyaku).permit(:event_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, class: "gravatar")
  end
end

app/views/abledates/index.html.erb
<h1>Abledate Search</h1>

<div class="search_form">
  <%= form_for @abledate_form, url: '#', method: :get do |f| %>
    <%= f.date_select :start %>
    <%= f.submit %>
  <% end %>
</div>

<div class="result">
  <% @abledates.each do |abledate| %>
    <<%= abledate.user_id %>
  <% end %>
</div>

app/views/events/_event.htlm.erb
<h2>
<li>
  <span class="reserve"><%= event.start %></span>
  <br />
  <span class="reserve"><%= event.user.username %></span>
</li>
</h2>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start %><br>
    <%= f.date_select :start %>
  </div>
  
  <!--
  <div class="field">
    <%= f.label :end %><br>
    <%= f.date_select :end %>
  </div>
  -->
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Booking</h1>

<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :booking %><br />
    <%= f.check_box :booking, {}, "true", "false" %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Start</th>
      <th>End</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.start %></td>
        <td><%= event.end %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>
<% if current_user.location == "Seattle" %>
Register Available Dates
<% elsif current_user.location == "Tokyo" %>
宿泊者受け入れ可能日を登録してください
<% end %>
</h1>

<%= render 'form' %>
<br />
<%= link_to 'Back', events_path %>
<div id="calendar"></div>

app/views/events/new_search.html.erb
<!-- <h1>Register Available Dates</h1><br /> -->
<h1>宿泊希望日で検索してください</h1>

<%= form_for(@event) do |f| %>

  <div class="field">
    <%= f.label :start %><br>
    <%= f.date_select :start %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% @hosts.each do |host| %>
  <%= host.name %><br />
<% end %>

app/views/events/search.html.erb
<h1>
<% if current_user.location == "Seattle" %>
Date Search
<% elsif current_user.location == "Tokyo" %>
宿泊希望日で検索してください
<% end %>
</h1>

<!-- 検索画面 -->
<%= form_tag search_path, method: :get do %>
 <div class="field">
   <%= date_select :start, params[:start] %>
   <%= submit_tag '検索' %>
 </div>
<% end %>

<!-- 結果表示 -->
<% if @dates.present? %>
  <% @dates.each do |date| %>
    <%= date.start %><br />
    <%= date.user.username %><br />
    <%= link_to "詳細", event_path(date) %><br />
    <%= link_to "予約", edit_event_path(date) %><br />
    <%= link_to "すぐ予約", search_path, method: :post %><br />
  <% end %>
<% end %>

app/views/events/searchform.html.erb
<h1>
<% if current_user.location == "Seattle" %>
Date Search
<% elsif current_user.location == "Tokyo" %>
宿泊希望日で検索してください
<% end %>
</h1>

<%= form_for(@event, url: event_search) do |f| %>
 <div class="field">
   <%= f.label :start %><br>
   <%= f.date_select :start %>
 </div>
 <br />
 <div class="actions">
   <%= f.submit %>
 </div>
<% end %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start:</strong>
  <br />
  <%= @event.id %>
  <br />
  <%= @event.start %>
  <br />
  <%= @event.user.username %>
</p>
<!--
<p>
  <strong>End:</strong>
  <%= @event.end %>
</p>
-->

<%= form_for(Reservation.new) do |f| %>
  <div><%= hidden_field_tag :event_id, @event.id %></div>
  <%= f.submit "Reserve", class: "btn btn-primary" %>
<% end %>

<%= link_to 'Edit', edit_event_path(@event) %>
<%= link_to 'Back', events_path %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Ourbnb", '#', id: "logo" %>
    <nav>
      <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to current_user.username + " @" + current_user.location, profile_path %></li>
        <% if current_user.location == "Seattle" %>
          <li><%= link_to "Tokyo Hosts", tokyohostlist_path %></li>
        <% elsif current_user.location == "Tokyo" %>
          <li><%= link_to "Seattle Hosts", seattlehostlist_path %></li>
        <% end %>
        <li><%= link_to "Search", event_search_form_path %></li>
        <% if current_user.hosting == true %>
          <li><%= link_to "Hosting Management", new_event_path %></li>
        <% else %>
          <li><%= link_to "Become a Host?", edit_user_registration_path %></li>       
        <% end %>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      </ul>
      <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to " ", new_user_registration_path %></li> <!-- Admin only, hidden -->
        <li><%= link_to "Log in", new_user_session_path %></li>
      </ul>
      <% end %>
    </nav>
  </div>
</header> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ourbnb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to Our Home!</h1>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/pages/profile.html.erb
<h1>
  <%= @user.username %>
</h1>
<p>
  <br />
  <h3>Email: <%= @user.email %></h3>
  <br />
  <h3>Location: <%= @user.location %></h3>
  <br />
  <% if current_user.hosting == true %>
    <h3>Host: Yes</h3>
  <% else %>
    <h3>Host: No</h3>
  <% end %>
  <br />
<p/>
<p>
  <%= link_to "Change Password?", edit_user_registration_path %>
  <br />
  <% if current_user.hosting == true %>
    <%= link_to "Unbecome a Host?", edit_user_registration_path %>
  <% else %>
    <%= link_to "Become a Host?", edit_user_registration_path %>
  <% end %>
</p>

<h3>Your Reservations</h3>
<h4>
<% @events.each do |event| %>
  <%= event.start %>  @ <%= event.user.username %>'s House<br />
<% end %>
</h4>

<!--
<% if @user.reservations.any? %>
  <h3>Your Reservations</h3>
  <ol class="reservation">
    <%= render @reservations %>
  </ol>
<% end %>
-->

<% if current_user.hosting == true %>
  <div id="calendar"></div>
<% end %>

app/views/pages/seattle_host_list.html.erb
<h3>
  Seattle Host List
</h3>
<br/>

<div class="col-md-8">
  <ol class="hosts">
    <%= render @seattlehosts %>
  </ol>
</div>

app/views/pages/tokyo_host_list.html.erb
<h1>
  Tokyo Host List
</h1>

<div class="col-md-8">
  <ol class="hosts">
    <%= render @tokyohosts %>
  </ol>
</div>

app/views/reservations/_reservation.html.erb
<h2>
<li>
  <span class="reserve"><%= reservation.user.username %></span>
  <br />
  <span class="reserve"><%= reservation.event %></span>
</li>
</h2>

app/views/users/_user.html.erb
<li>
  <%= link_to gravatar_for(user, size: 50) %>
  <span class="user"><%= link_to user.username %></span>
  <br />
  <br />
  <br />
</li>

app/views/yoyakus/_yoyaku.html.erb
<h2>
<li>
  <span class="yoyaq"><%= yoyaku.user.username %></span>
  <br />
  <span class="yoyaq"><%= yoyaku.event %></span>
</li>
</h2>